name: Update XNA CnCNet Client Release

on:
  workflow_dispatch:  # This allows manual triggering from GitHub Actions UI

env:
  REPO_NAME: TwistedInsurrectionUpdatedClient
  UPDATE_BRANCH_NAME: update-client-binaries
  COMMIT_MESSAGE: Update client binaries to the latest version
  PR_TITLE: Update client binaries to the latest version
  PR_BODY: This is an automatic pull request to update client binaries triggered from CnCNet/xna-cncnet-client repository.

jobs:
  make-update-pr:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download latest XNA client release
      uses: robinraju/release-downloader@v1
      with:
        repository: CnCNet/xna-cncnet-client
        latest: true
        fileName: xna-cncnet-client*

    - name: Extract release contents
      run: |
        7z x xna-cncnet-client-*.7z -oD:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}
        rm xna-cncnet-client-*.7z
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    - name: Check for changes
      id: check_changes
      run: |
        if (git status --porcelain) {
          echo "changed=true" >> $env:GITHUB_ENV
        } else {
          echo "changed=false" >> $env:GITHUB_ENV
        }
    - name: Commit and push changes
      if: env.changed == 'true'
      run: |
        git checkout -b ${{ env.UPDATE_BRANCH_NAME }}
        git add Resources
        git commit -m "${{ env.COMMIT_MESSAGE }}"
        git push origin ${{ env.UPDATE_BRANCH_NAME }}
    - name: Create Pull Request
      if: env.changed == 'true'
      run: gh pr create -B main -H ${{ env.UPDATE_BRANCH_NAME }} --title '${{ env.PR_TITLE }}' --body '${{ env.PR_BODY }}'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
